### ISSUE TITLE
Add parser for "raw"

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-onboarding#249]
### Environment
* Nautobot version:  2.2+
* nautobot-device-onboarding version:  4.0.1

### Proposed Functionality
Ability to run a command and get raw output and skip jpath and do post_processor.

### Use Case
Certain platforms configuration has easy easier accessiblility to data fields by just manually parsing / simple raw processing.  For example hp_comware 

```yaml
  hostname:
    commands:
      - command: "display current | include sysname"
        parser: "raw"
        jpath: "raw"
        post_processor: "{{ obj.lstrip().split(' ')[1] }}"
```
