### ISSUE TITLE
Modifying hp_comware command mappers to support IRF stacks

### ISSUE THREAD

**Issue by marcus-cain** [nautobot/nautobot-app-device-onboarding#292]
### Environment
* Nautobot version:  2.3.13
* nautobot-device-onboarding version:   Example: 4.1.0 
* Note - I have scrubbed some of the output, but can provide details job logs if needed

### Proposed Functionality
The current version of the device onboarding app (4.1.0) supports non-irf (not in a stack) HP comware devices via the SSOTSyncDevices Job. Evidence of this will be posted below. I understand NTC hasn't yet fully thought about all the various stack and virtual chassis scenarios for each platform, as those discussions are still being had. However, in the meantime, i propose following exactly what the current app is doing for IOSXE devices. The SSOTSyncDevices Job is able to handle stacked iosxe devices, because the command mapper for iosxe is using the jinja post_processor  {{ obj | unique | first }}, which is basically taking the first item in the list that get returned.

In order to follow the same strategy for HP comware devices in an IRF stack (which is HP equivalent of cisco stackwise technology), i propose making the following modifications to the serial and device_type keys in the command mapper

```
  serial:
    commands:
      - command: "display device manuinfo"
        parser: "textfsm"
        jpath: "[?slot_type==`Slot`].device_serial_number"
        post_processor: "{{ obj | unique | first }}" #added to grab the first serial, which is the serial of the switch member being logged into
  device_type:
    commands:
      - command: "display device manuinfo"
        parser: "textfsm"
        jpath: "[?slot_type==`Slot`].device_name"
        post_processor: "{{ obj | unique | first }}"#added to grab the first model, which is the model/partnumber of the switch member being logged into
```

### Use Case
The use case is to have the device onboarding application be able to onboard hp comware switches in an IRF stack in the same manner that device onboarding is handling cisco iosxe switches in a stackwise setup. The proposed implementation wouldn't account for different models being in an IRF stack, since the proposed solution is to take the 1st item in the return list, but the same is true for the cisco iosxe devices that device onboarding currently supports.

### Testing Results
I have testing this on the following comware devices for both IRF and non-IRF scenarios:
 - Hp 5900AF-48XG-4QSFP+ JC772A
 - Hp 5900AF-48XG-4QSFP+ JC772A
 - Hp FlexFabric 5930-4Slot JH179A

**Below is the full onboarding_command_mappers override file for hp_comware**

```
sync_devices:
  hostname:
    commands:
      - command: "display current | include sysname"
        parser: "raw"
        jpath: "raw"
        post_processor: "{{ obj.lstrip().split(' ')[1] }}"
  serial:
    commands:
      - command: "display device manuinfo"
        parser: "textfsm"
        jpath: "[?slot_type==`Slot`].device_serial_number"
        post_processor: "{{ obj | unique | first }}" #added
  device_type:
    commands:
      - command: "display device manuinfo"
        parser: "textfsm"
        jpath: "[?slot_type==`Slot`].device_name"
        post_processor: "{{ obj | unique | first }}" #added
  mgmt_interface:
    commands:
      - command: "display ip interface"
        parser: "textfsm"
        jpath: "[*].{interface: interface, ip_addr: ip_address[0]}"
        post_processor: "{% for i in obj %}{% if i['ip_addr'] %}{% if original_host in i['ip_addr'] %}{{ i['interface'] }}{% endif %}{% endif %}{% endfor %}"
  mask_length:
    commands:
      - command: "display ip interface"
        parser: "textfsm"
        jpath: "[*].ip_address[?contains(@, `{{ obj }}`)][]"
        post_processor: "{{ obj[0].split('/')[1] }}"
        iterable_type: "int"
```

&nbsp;  
&nbsp;  
&nbsp;  
**Below are the testing results**

> - NON IRF switch works as intended with current onboarding command mappers
>  - Hp 5900AF-48XG-4QSFP+ JC772A

 

```
 <SwitchScrubbedHostname>dis irf
MemberID    Role    Priority  CPU-Mac         Description
 *+1        Master  32        00e0-fc0f-8c02  SwitchScrubbedDescription
--------------------------------------------------
 * indicates the device is the master.
 + indicates the device through which the user logs in.
```
![image](https://github.com/user-attachments/assets/525e27a0-15c1-4b09-8cc9-d5b35944d053)
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  

> - IRF switch of same model doesn't work as the current command mapper doesn't know how to extract data from the returned list
>  - Hp 5900AF-48XG-4QSFP+ JC772A

```
<SwitchScrubbedHostname>dis irf
MemberID    Role    Priority  CPU-Mac         Description
 *+1        Master  32        00e0-fc0f-8c02  SwitchScrubbedDescription-1
   2        Standby 1         00e0-fc0f-8c03  SwitchScrubbedDescription-2
--------------------------------------------------
 * indicates the device is the master.
 + indicates the device through which the user logs in.
```

![image](https://github.com/user-attachments/assets/9f84f917-71ea-4923-a827-0c31b73003d9)

Current JMESPath expression results in a list
![image](https://github.com/user-attachments/assets/51cc8dc1-a74f-4349-9b74-37db87e09342)
![image](https://github.com/user-attachments/assets/9c629574-f51a-4a45-83e7-ba0876e3b9ae)

&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
**After Overriding the Command Mapper with the YML file above**
> - IRF switch of same model now works as the current command mapper does post processing to grab the first item in the return listed
>  - Hp 5900AF-48XG-4QSFP+ JC772A

```
<SwitchScrubbedHostname>dis irf
MemberID    Role    Priority  CPU-Mac         Description
 *+1        Master  32        00e0-fc0f-8c02  SwitchScrubbedDescription-1
   2        Standby 1         00e0-fc0f-8c03  SwitchScrubbedDescription-2
--------------------------------------------------
 * indicates the device is the master.
 + indicates the device through which the user logs in.
```
![image](https://github.com/user-attachments/assets/dfd66b80-fdcf-4578-b2bb-886a000d2492)
![image](https://github.com/user-attachments/assets/56409d0e-41de-4970-aa63-5aa44c55a4d3)
